In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

df = pd.read_csv("mo_features.csv")
display(df)

,FV_avg_avg,FV_avg_sd,FV_sd_avg,FV_sd_sd,FV_r1_avg,FV_r1_sd,FV_kr_avg,FV_kr_sd,FV_sk_avg,FV_sk_sd,FD_avg_avg,FD_avg_sd,FD_sd_avg,FD_sd_sd,FD_r1_avg,FD_r1_sd,FD_kr_avg,FD_kr_sd,FD_sk_avg,FD_sk_sd,IN_avg_avg,IN_avg_sd,IN_sd_avg,IN_sd_sd,IN_r1_avg,IN_r1_sd,IN_kr_avg,IN_kr_sd,IN_sk_avg,IN_sk_sd
0,5.899826e+07,3.825064e+07,632790.283285,444047.451903,0.278888,0.270142,2.667967,1.474598,0.556821,0.754754,0.083351,0.221392,0.071115,0.197985,-0.086414,0.205497,2.640288,0.910404,0.64123,0.521934,0.4175,0.138767,0.351651,0.065413,-0.034781,0.404627,1.908812,0.527922,0.335634,0.520826

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FV_avg_avg  1 non-null      float64
 1   FV_avg_sd   1 non-null      float64
 2   FV_sd_avg   1 non-null      float64
 3   FV_sd_sd    1 non-null      float64
 4   FV_r1_avg   1 non-null      float64
 5   FV_r1_sd    1 non-null      float64
 6   FV_kr_avg   1 non-null      float64
 7   FV_kr_sd    1 non-null      float64
 8   FV_sk_avg   1 non-null      float64
 9   FV_sk_sd    1 non-null      float64
 10  FD_avg_avg  1 non-null      float64
 11  FD_avg_sd   1 non-null      float64
 12  FD_sd_avg   1 non-null      float64
 13  FD_sd_sd    1 non-null      float64
 14  FD_r1_avg   1 non-null      float64
 15  FD_r1_sd    1 non-null      float64
 16  FD_kr_avg   1 non-null      float64
 17  FD_kr_sd    1 non-null      float64
 18  FD_sk_avg   1 non-null      float64
 19  FD_sk_sd    1 non-null      float64
 20  IN_avg_avg  1 non-null      float64
 21  IN_avg_sd   1 non-null      float64
 22  IN_sd_avg   1 non-null      float64
 23  IN_sd_sd    1 non-null      float64
 24  IN_r1_avg   1 non-null      float64
 25  IN_r1_sd    1 non-null      float64
 26  IN_kr_avg   1 non-null      float64
 27  IN_kr_sd    1 non-null      float64
 28  IN_sk_avg   1 non-null      float64
 29  IN_sk_sd    1 non-null      float64
dtypes: float64(30)
memory usage: 372.0 bytes